//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreScripds.UI.OrganizationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrganizationServiceReference.IOrganizationService")]
    public interface IOrganizationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationService/GetOrganizationById", ReplyAction="http://tempuri.org/IOrganizationService/GetOrganizationByIdResponse")]
        PreScripds.Domain.Organization GetOrganizationById(long organizationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrganizationService/GetOrganizationById", ReplyAction="http://tempuri.org/IOrganizationService/GetOrganizationByIdResponse")]
        System.Threading.Tasks.Task<PreScripds.Domain.Organization> GetOrganizationByIdAsync(long organizationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrganizationServiceChannel : PreScripds.UI.OrganizationServiceReference.IOrganizationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrganizationServiceClient : System.ServiceModel.ClientBase<PreScripds.UI.OrganizationServiceReference.IOrganizationService>, PreScripds.UI.OrganizationServiceReference.IOrganizationService {
        
        public OrganizationServiceClient() {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrganizationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PreScripds.Domain.Organization GetOrganizationById(long organizationId) {
            return base.Channel.GetOrganizationById(organizationId);
        }
        
        public System.Threading.Tasks.Task<PreScripds.Domain.Organization> GetOrganizationByIdAsync(long organizationId) {
            return base.Channel.GetOrganizationByIdAsync(organizationId);
        }
    }
}
