//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreScripds.UI.UserServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/PreScripds.Domain", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private sbyte activeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> approved_byField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime created_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int department_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> dobField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> genderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<sbyte> isapprovedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> last_login_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string login_ipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long mobileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string recovery_emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> recovery_phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int roleidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string salt_keyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime updated_dateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long user_idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte active {
            get {
                return this.activeField;
            }
            set {
                if ((this.activeField.Equals(value) != true)) {
                    this.activeField = value;
                    this.RaisePropertyChanged("active");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> approved_by {
            get {
                return this.approved_byField;
            }
            set {
                if ((this.approved_byField.Equals(value) != true)) {
                    this.approved_byField = value;
                    this.RaisePropertyChanged("approved_by");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime created_date {
            get {
                return this.created_dateField;
            }
            set {
                if ((this.created_dateField.Equals(value) != true)) {
                    this.created_dateField = value;
                    this.RaisePropertyChanged("created_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int department_id {
            get {
                return this.department_idField;
            }
            set {
                if ((this.department_idField.Equals(value) != true)) {
                    this.department_idField = value;
                    this.RaisePropertyChanged("department_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> dob {
            get {
                return this.dobField;
            }
            set {
                if ((this.dobField.Equals(value) != true)) {
                    this.dobField = value;
                    this.RaisePropertyChanged("dob");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<sbyte> isapproved {
            get {
                return this.isapprovedField;
            }
            set {
                if ((this.isapprovedField.Equals(value) != true)) {
                    this.isapprovedField = value;
                    this.RaisePropertyChanged("isapproved");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> last_login_date {
            get {
                return this.last_login_dateField;
            }
            set {
                if ((this.last_login_dateField.Equals(value) != true)) {
                    this.last_login_dateField = value;
                    this.RaisePropertyChanged("last_login_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastname {
            get {
                return this.lastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastnameField, value) != true)) {
                    this.lastnameField = value;
                    this.RaisePropertyChanged("lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string login_ip {
            get {
                return this.login_ipField;
            }
            set {
                if ((object.ReferenceEquals(this.login_ipField, value) != true)) {
                    this.login_ipField = value;
                    this.RaisePropertyChanged("login_ip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long mobile {
            get {
                return this.mobileField;
            }
            set {
                if ((this.mobileField.Equals(value) != true)) {
                    this.mobileField = value;
                    this.RaisePropertyChanged("mobile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string recovery_email {
            get {
                return this.recovery_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.recovery_emailField, value) != true)) {
                    this.recovery_emailField = value;
                    this.RaisePropertyChanged("recovery_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> recovery_phone {
            get {
                return this.recovery_phoneField;
            }
            set {
                if ((this.recovery_phoneField.Equals(value) != true)) {
                    this.recovery_phoneField = value;
                    this.RaisePropertyChanged("recovery_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int roleid {
            get {
                return this.roleidField;
            }
            set {
                if ((this.roleidField.Equals(value) != true)) {
                    this.roleidField = value;
                    this.RaisePropertyChanged("roleid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string salt_key {
            get {
                return this.salt_keyField;
            }
            set {
                if ((object.ReferenceEquals(this.salt_keyField, value) != true)) {
                    this.salt_keyField = value;
                    this.RaisePropertyChanged("salt_key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime updated_date {
            get {
                return this.updated_dateField;
            }
            set {
                if ((this.updated_dateField.Equals(value) != true)) {
                    this.updated_dateField = value;
                    this.RaisePropertyChanged("updated_date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserServiceReference.IUserService")]
    public interface IUserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        PreScripds.UI.UserServiceReference.User[] GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUserService/GetUsers", ReplyAction="http://tempuri.org/IUserService/GetUsersResponse")]
        System.Threading.Tasks.Task<PreScripds.UI.UserServiceReference.User[]> GetUsersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUserServiceChannel : PreScripds.UI.UserServiceReference.IUserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<PreScripds.UI.UserServiceReference.IUserService>, PreScripds.UI.UserServiceReference.IUserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PreScripds.UI.UserServiceReference.User[] GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Threading.Tasks.Task<PreScripds.UI.UserServiceReference.User[]> GetUsersAsync() {
            return base.Channel.GetUsersAsync();
        }
    }
}
