//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PreScripds.Test.MasterServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MasterServiceReference.IMasterService")]
    public interface IMasterService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterService/GetDepartments", ReplyAction="http://tempuri.org/IMasterService/GetDepartmentsResponse")]
        PreScripds.Domain.Department[] GetDepartments();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMasterService/GetDepartments", ReplyAction="http://tempuri.org/IMasterService/GetDepartmentsResponse")]
        System.Threading.Tasks.Task<PreScripds.Domain.Department[]> GetDepartmentsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMasterServiceChannel : PreScripds.Test.MasterServiceReference.IMasterService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MasterServiceClient : System.ServiceModel.ClientBase<PreScripds.Test.MasterServiceReference.IMasterService>, PreScripds.Test.MasterServiceReference.IMasterService {
        
        public MasterServiceClient() {
        }
        
        public MasterServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MasterServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MasterServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PreScripds.Domain.Department[] GetDepartments() {
            return base.Channel.GetDepartments();
        }
        
        public System.Threading.Tasks.Task<PreScripds.Domain.Department[]> GetDepartmentsAsync() {
            return base.Channel.GetDepartmentsAsync();
        }
    }
}
